import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar, NavbarBrand, NavbarCollapse, NavbarLink, NavbarToggle } from "flowbite-react";
import Image from "next/image";
import Link from "next/link";
import { Barlow, Goldman } from 'next/font/google';

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-barlow",
});

const goldman = Goldman({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-goldman",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${goldman.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar fluid rounded className="justify-between mx-auto p-4 bg-[#eeeeee] dark:bg-[#eeeeee] fixed top-0 right-0 left-0 z-50">
          <NavbarBrand as={Link} href="/" className="space-x-3 sm:pl-[9%]">
            <Image
              src={'/images/logo.svg'}
              alt="logo image"
              width={13.27}
              height={39.5}
            />
            <Image
              src={'/images/nom-logo.svg'}
              alt="nom logo"
              width={130}
              height={20}
            />
          </NavbarBrand>
          <NavbarToggle />
          <NavbarCollapse className="font-medium p-4 md:p-0 mt-4 md:pr-[9%]">
            <NavbarLink href="#" className="text-[#394149] dark:text-[#394149] text-[18px]">
              Acceuil
            </NavbarLink>
            <NavbarLink href="#" className="text-[#394149] dark:text-[#394149] text-[18px]">A propos</NavbarLink>
            <NavbarLink href="#" className="text-[#394149] dark:text-[#394149] text-[18px]">Forfait</NavbarLink>
            <NavbarLink href="#" className="text-[#394149] dark:text-[#394149] text-[18px]">Contact</NavbarLink>
            <NavbarLink href="#" className="text-[#394149] dark:text-[#394149] text-[18px]">Nous soutenir</NavbarLink>
          </NavbarCollapse>
        </Navbar>
        {children}
      </body>
    </html>
  );
}
